name: Custom Release Build

on:
  workflow_dispatch:

jobs:

  build-windows:
    name: Windows
    runs-on: windows-latest

    env:
      PREPARE_PATH: "Telegram/build/prepare/prepare.py"
      TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
      TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
      TBUILD: ${{ github.workspace }}\TBuild

    defaults:
      run:
        shell: cmd

    steps:
      - name: Init Build Directories
        run: |
          mkdir %TBUILD%\Libraries
          mklink /d %GITHUB_WORKSPACE%\TBuild %TBUILD%

      - name: Get Repository Name
        shell: bash
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - uses: ilammy/msvc-dev-cmd@v1
        name: MSVC Dev Environment
        with:
          arch: x64

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          path: "${{ format('{0}\\tdesktop', env.TBUILD) }}"

      - name: ThirdParty Cache
        uses: actions/cache@v4
        with:
          path: "${{ env.TBUILD }}\\ThirdParty"
          key: ${{ runner.os }}-thirdparty-${{ hashFiles(format('{0}\\{1}', env.REPO_NAME, env.PREPARE_PATH)) }}

      - name: Libraries Cache
        uses: actions/cache@v4
        with:
          path: "${{ env.TBUILD }}\\Libraries"
          key: ${{ runner.os }}-libraries-${{ hashFiles(format('{0}\\{1}', env.REPO_NAME, env.PREPARE_PATH)) }}

      - name: Prepare Libraries
        run: |
          cd %TBUILD%
          %REPO_NAME%\Telegram\build\prepare\win.bat skip-release silent

      - name: Configure and Build
        run: |
          cd %TBUILD%\%REPO_NAME%\Telegram
          call configure.bat x64 ^
            -D CMAKE_C_FLAGS="/WX" ^
            -D CMAKE_CXX_FLAGS="/WX" ^
            -D DESKTOP_APP_DISABLE_AUTOUPDATE=ON ^
            -D DESKTOP_APP_DISABLE_CRASH_REPORTS=ON ^
            -D DESKTOP_APP_NO_PDB=ON ^
            -D TDESKTOP_API_ID=%TELEGRAM_API_ID% ^
            -D TDESKTOP_API_HASH=%TELEGRAM_API_HASH%
          cmake --build ..\out --config Release

      - name: Package Windows ZIP
        run: |
          cd %TBUILD%\%REPO_NAME%\out\Release
          mkdir artifact
          copy Telegram.exe artifact\
          powershell -Command "Compress-Archive -Path artifact\* -DestinationPath telegram-windows.zip"

      - name: Upload Windows ZIP
        uses: actions/upload-artifact@v4
        with:
          name: telegram-windows
          path: "${{ env.TBUILD }}\\${{ env.REPO_NAME }}\\out\\Release\\telegram-windows.zip"

  build-macos:
    name: macOS
    runs-on: macos-13

    env:
      PREPARE_PATH: "Telegram/build/prepare/prepare.py"
      TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
      TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}

    steps:
      - name: Get Repository Name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          path: ${{ env.REPO_NAME }}

      - name: Install Build Dependencies
        run: |
          brew install automake meson nasm ninja pkg-config create-dmg
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: ThirdParty Cache
        uses: actions/cache@v4
        with:
          path: ThirdParty
          key: macos-thirdparty-${{ hashFiles(format('{0}/{1}', env.REPO_NAME, env.PREPARE_PATH)) }}

      - name: Libraries Cache
        uses: actions/cache@v4
        with:
          path: Libraries
          key: macos-libraries-${{ hashFiles(format('{0}/{1}', env.REPO_NAME, env.PREPARE_PATH)) }}

      - name: Prepare Libraries
        run: ./${{ env.REPO_NAME }}/Telegram/build/prepare/mac.sh skip-release silent

      - name: Configure and Build
        run: |
          cd $REPO_NAME/Telegram
          ./configure.sh \
            -D CMAKE_C_FLAGS="-Werror" \
            -D CMAKE_CXX_FLAGS="-Werror" \
            -D CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO \
            -D TDESKTOP_API_TEST=OFF \
            -D DESKTOP_APP_DISABLE_AUTOUPDATE=ON \
            -D DESKTOP_APP_DISABLE_CRASH_REPORTS=ON \
            -D TDESKTOP_API_ID=${TELEGRAM_API_ID} \
            -D TDESKTOP_API_HASH=${TELEGRAM_API_HASH}
          cd ../out
          xcodebuild -project Telegram.xcodeproj -scheme Telegram -configuration Release -arch arm64

      - name: Package macOS DMG
        run: |
          cd $REPO_NAME/out/Release
          create-dmg --volname "Telegram" \
            --window-size 800 400 \
            --icon "Telegram.app" 200 190 \
            --app-drop-link 600 185 \
            Telegram.dmg Telegram.app

      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: telegram-macos
          path: ${{ env.REPO_NAME }}/out/Release/Telegram.dmg
